"""Seeded neutral shapes the KPI ledger measures, and the one whole run each goes through.

Every shape here is built at runtime from a fixed seed (plan D13): no
table enters the repository. Each builder names the ledger entry it
serves, and was ported from the measurement driver that first produced
the entry's number, so the number in `tests/kpi/ledger.json` can be
re-derived by running the test that owns it.

A whole run is the product's own path and nothing else: the table is
written to disk, read by the real reader, described by the real
producer, loaded by the strict loader, generated by the real generator
and checked by the real validator. Nothing is stubbed.
"""

from __future__ import annotations

import contextlib
import csv
import datetime
import io
import json
import pathlib
import random
import sys

import fixtures
import workbooks
from synthtwin import (
    cli,
    contract,
    generation,
    profile,
    reading,
    rendering,
    taxonomy,
    validation,
)

# The golden demonstration's seed (tests/test_twin_golden.py).
GOLDEN_SEED = 20260811
# The seed the realistic shapes were first measured at.
SHAPE_SEED = "4"


# -- one whole run, in process ------------------------------------------


class Described:
    """A table on disk, its description document and the loaded profile."""

    def __init__(
        self,
        folder: pathlib.Path,
        table: pathlib.Path,
        document: "dict",
        loaded: contract.Profile,
    ) -> None:
        self.folder = folder
        self.table = table
        self.document = document
        self.loaded = loaded

    def block(self, name: str) -> "dict":
        """The description block of one named column."""
        for block in self.document["columns"]:
            if block["name"] == name:
                return block
        raise AssertionError(f"no column {name!r}")


def describe(
    folder: pathlib.Path,
    stem: str,
    text: str,
    floor: "int | None" = None,
    declared: "list[str] | None" = None,
    codes: "list[str] | None" = None,
    measured: "list[str] | None" = None,
    first_row: str = reading.FIRST_ROW_AUTOMATIC,
) -> Described:
    """Write ``text`` as a table and describe it; ``floor`` None is the shipped default."""
    folder.mkdir(parents=True, exist_ok=True)
    table = fixtures.write(folder, f"{stem}.csv", text)
    settings = (
        taxonomy.Settings()
        if floor is None
        else taxonomy.Settings(small_cell_floor=floor)
    )
    # READ AT THE FLOOR IT IS DESCRIBED AT (plan P4-D317). The reader
    # asks the file's line rules at its own floor, so a table read at one
    # floor and described at another publishes a form no description at
    # the described floor would.
    document = profile.build_document(
        reading.read_table(
            str(table),
            first_row=first_row,
            small_cell_floor=settings.small_cell_floor,
        ),
        settings,
        declared or [],
        codes or [],
        measured or [],
    )
    written = fixtures.write_profile(folder, f"{stem}-profile.json", document)
    return Described(folder, table, document, contract.load_profile(str(written)))


def twin_text(described: Described, seed: int) -> str:
    """The twin's exact bytes, as `synthtwin generate` writes them."""
    return rendering.twin_csv(generation.generate(described.loaded, seed))


def measure(described: Described, text: str, name: str) -> validation.Outcome:
    """Validate a file holding ``text`` against the description."""
    target = fixtures.write(described.folder, name, text)
    return validation.measure(described.loaded, str(target))


def missed(outcome: validation.Outcome) -> "list[str]":
    """Every MISSED verdict as 'column:subcheck', with no carve-out."""
    return sorted(
        f"{check.column}:{check.subcheck}"
        for check in outcome.checks
        if check.verdict == validation.MISSED
    )


def every_role(folder: pathlib.Path, floor: "int | None", headed: bool = True) -> Described:
    """The every-role table with its joined column (tests/test_validation.py's run).

    Headed, the record number is declared and the pressure column is a
    measurement. Headerless, the header line is taken off and the first
    row is declared a record, so nothing can be declared by name.
    """
    text = fixtures.every_role_and_joined_table()
    if headed:
        return describe(
            folder,
            f"every-role-{floor}",
            text,
            floor,
            ["record_code"],
            measured=[fixtures.JOINED_COLUMN],
        )
    bare = text.split("\n", 1)[1]
    return describe(
        folder,
        f"every-role-bare-{floor}",
        bare,
        floor,
        first_row=reading.FIRST_ROW_DATA,
    )


def quiet_cli(argv: "list[str]") -> int:
    """One synthtwin command in this process, its screen output swallowed."""
    before = sys.argv
    sys.argv = ["synthtwin"] + argv
    try:
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(
            io.StringIO()
        ):
            try:
                code = cli.main()
            except SystemExit as stop:
                code = 0 if stop.code is None else int(stop.code)
    finally:
        sys.argv = before
    return code


def cycle(
    path: pathlib.Path, flags: "list[str]", seed: str = SHAPE_SEED,
    generate: bool = True, validate: bool = True,
) -> "dict":
    """profile, generate, validate the twin AND the real file, through the command line.

    Returns the four exit codes (None for a step not run) and the paths
    the run left. A measurement that needs only the description, or only
    the twin, asks for less and costs less.
    """
    folder = path.parent
    out: "dict" = {"profile": quiet_cli(
        ["profile", str(path), "--out-dir", str(folder), "--replace", *flags]
    )}
    description = folder / (path.stem + "-profile.json")
    twin = folder / (path.stem + "-twin" + path.suffix)
    out["description"] = description
    out["twin"] = twin
    out["generate"] = out["validate_twin"] = out["validate_real"] = None
    if out["profile"] != 0 or not generate:
        return out
    out["generate"] = quiet_cli(
        ["generate", str(description), "--out-dir", str(folder), "--seed", seed, "--replace"]
    )
    if out["generate"] != 0 or not twin.exists() or not validate:
        return out
    for side, checked in (("validate_twin", twin), ("validate_real", path)):
        report = folder / side
        report.mkdir(exist_ok=True)
        out[side] = quiet_cli(
            ["validate", str(description), "--twin", str(checked), "--out-dir",
             str(report), "--replace"]
        )
    return out


def csv_rows(path: pathlib.Path) -> "list[list[str]]":
    """A delimited file's rows, header included, whatever its mark and byte-order mark."""
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    text = raw.decode("utf-8")
    first = text.split("\n", 1)[0]
    mark = ";" if first.count(";") > first.count(",") else ","
    return list(csv.reader(io.StringIO(text, newline=""), delimiter=mark))


def row_copies(
    real: "list[list[str]]", twin: "list[list[str]]", ignore: "int | None"
) -> "tuple[int, int]":
    """(twin rows equal to a whole real row, twin rows equal to one ignoring a column).

    Both lists start with their header, which is not counted.
    """
    whole = {tuple(row) for row in real[1:]}

    def without(row: "list[str]") -> "tuple[str, ...]":
        return tuple(v for place, v in enumerate(row) if place != ignore)

    partial = {without(row) for row in real[1:]}
    copies = sum(1 for row in twin[1:] if tuple(row) in whole)
    near = sum(1 for row in twin[1:] if without(row) in partial)
    return copies, near


# -- the eight realistic shapes (K-2B-40, K-P2-05, K-2B-45, K-2B-46) ------
#
# Ported from the stage-2b files-and-trust miner's shapes8.py: four
# families, each written once as delimited text and once as a workbook,
# 400 rows, first measured at seed 4.

EIGHT_ROWS = 400


def _delimited(
    path: pathlib.Path,
    names: "list[str]",
    rows: "list[list[str]]",
    mark: str = ",",
    newline: str = "\n",
    bom: bool = False,
) -> None:
    out = io.StringIO()
    writer = csv.writer(out, delimiter=mark, lineterminator=newline)
    writer.writerow(names)
    writer.writerows(rows)
    data = out.getvalue().encode("utf-8")
    path.write_bytes((b"\xef\xbb\xbf" if bom else b"") + data)


def _plain_styles() -> bytes:
    parts = [
        workbooks._DECLARATION,
        f'<styleSheet xmlns="{workbooks._MAIN}">',
        '<numFmts count="0"></numFmts>',
        '<fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts>',
        '<fills count="2"><fill><patternFill patternType="none"/></fill>'
        '<fill><patternFill patternType="gray125"/></fill></fills>',
        '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/>'
        "</border></borders>",
        '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" '
        'borderId="0"/></cellStyleXfs>',
        '<cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" '
        'borderId="0" xfId="0"/></cellXfs>',
        '<cellStyles count="1"><cellStyle name="Normal" xfId="0" '
        'builtinId="0"/></cellStyles>',
        "</styleSheet>",
    ]
    return "".join(parts).encode("utf-8")


def _workbook(path: pathlib.Path, names: "list[str]", rows: "list[list[str]]") -> None:
    body = [
        (
            1,
            [
                workbooks.cell(f"{workbooks._column(place + 1)}1", name, kind="inlineStr")
                for place, name in enumerate(names)
            ],
        )
    ]
    for place, row in enumerate(rows):
        number = place + 2
        body += [
            (
                number,
                [
                    workbooks.cell(
                        f"{workbooks._column(i + 1)}{number}", value, kind="inlineStr"
                    )
                    for i, value in enumerate(row)
                ],
            )
        ]
    last = f"{workbooks._column(len(names))}{len(rows) + 1}"
    path.write_bytes(
        workbooks.package(
            [
                ("[Content_Types].xml", workbooks._content_types(1, False, False, False)),
                ("_rels/.rels", workbooks._root_rels()),
                ("xl/workbook.xml", workbooks._workbook([("Data", "")])),
                ("xl/_rels/workbook.xml.rels", workbooks._workbook_rels(1, False)),
                ("xl/styles.xml", _plain_styles()),
                ("xl/worksheets/sheet1.xml", workbooks.sheet(body, dimension=f"A1:{last}")),
            ]
        )
    )


def eight_shape_tables() -> "list[dict]":
    """The four families' names, rows, declarations and delimited-file dialect.

    Family A is the files family (semicolons, CRLF, a byte-order mark and
    a declared record number), B the dates family, C the numbers family
    and D the labels family (a declared subject number, a lone re-cased
    label and 'NA' holes).
    """
    draw = random.Random(9)
    out = []
    rows = [
        [f"A-{1000 + i}", draw.choice(["North", "South", "East", "West"]), f"visit {i % 9}"]
        for i in range(EIGHT_ROWS)
    ]
    out += [dict(family="A", names=["record", "site", "note"], rows=rows,
                 identifier="record", mark=";", newline="\r\n", bom=True)]
    first = datetime.date(2021, 1, 1)
    rows = []
    for i in range(EIGHT_ROWS):
        day = first + datetime.timedelta(days=i % 250)
        stamp = day.strftime("%Y-%m-%dT%H:%M:%S").replace(
            "T00:00:00", f"T{8 + i % 9:02d}:{i % 60:02d}:00"
        ) + ("+01:00" if i % 2 else "Z")
        rows += [[day.strftime("%d-%b-%Y"), stamp, draw.choice(["North", "South"])]]
    out += [dict(family="B", names=["taken_on", "seen_at", "site"], rows=rows,
                 identifier=None, mark=",", newline="\n", bom=False)]
    rows = []
    for i in range(EIGHT_ROWS):
        amount = 1000 + i * 7.25
        text = f"{amount:,.2f}"
        if i % 37 == 0:
            text = f"({amount:,.2f})"
        rows += [[text, f"{(i % 40) + 0.5:.1f} mg", draw.choice(["North", "South", "East"])]]
    out += [dict(family="C", names=["amount", "dose", "site"], rows=rows,
                 identifier=None, mark=",", newline="\n", bom=False)]
    labels = (
        ["treated"] * 200 + ["control"] * 180 + ["withdrawn"] * 12
        + ["screen-fail"] * 3 + ["Treated"] * 2 + ["NA"] * 3
    )
    draw.shuffle(labels)
    rows = [
        [f"SUBJ{i:04d}", labels[i], draw.choice(["yes", "no", "n/a"])]
        for i in range(EIGHT_ROWS)
    ]
    out += [dict(family="D", names=["subject", "arm", "outcome"], rows=rows,
                 identifier="subject", mark=",", newline="\n", bom=False)]
    return out


def eight_shapes(home: pathlib.Path, floors: "tuple[int, ...]") -> "list[dict]":
    """Every family, delimited and workbook, through a whole run at each floor."""
    results = []
    for floor in floors:
        for family in eight_shape_tables():
            for kind in ("csv", "xlsx"):
                folder = home / f"{family['family']}_{kind}_{floor}"
                folder.mkdir(parents=True)
                path = folder / f"real.{kind}"
                if kind == "csv":
                    _delimited(path, family["names"], family["rows"], family["mark"],
                               family["newline"], family["bom"])
                else:
                    _workbook(path, family["names"], family["rows"])
                flags = ["--smallest-group", str(floor)]
                if family["identifier"]:
                    flags += ["--identifier", family["identifier"]]
                run = cycle(path, flags)
                run.update(family=family["family"], kind=kind, floor=floor,
                           path=path, family_spec=family)
                results += [run]
    return results


# -- the association baseline (K-S6-01) ---------------------------------


def association_table() -> str:
    """1,000 rows: sbp is built from age, and the death rate depends on age.

    Ported from the completeness critic's corr.py (Random(5)).
    """
    draw = random.Random(5)
    lines = ["age,sbp,group,died"]
    for _ in range(1000):
        age = draw.gauss(55, 12)
        sbp = 100 + 0.8 * age + draw.gauss(0, 8)
        group = draw.choice("FM")
        died = "yes" if draw.random() < (0.6 if age > 65 else 0.1) else "no"
        lines += [f"{age:.0f},{sbp:.0f},{group},{died}"]
    return "\n".join(lines) + "\n"


# -- the identifier room and the other privacy shapes (K-2B-18/28/30) ----
#
# Ported from the stage-2b privacy miner's measure.py.


def delimited_text(header: "list[str]", rows: "list[list[str]]") -> str:
    """A header and rows as comma-separated text with newline endings."""
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(header)
    writer.writerows(rows)
    return buffer.getvalue()


def privacy_trip(
    folder: pathlib.Path, header: "list[str]", rows: "list[list[str]]",
    flags: "list[str]", seed: str = SHAPE_SEED,
    generate: bool = True, validate: bool = True,
) -> "tuple[dict, list[list[str]], dict]":
    """A command-line run of one small table: (description, twin rows, exits)."""
    folder.mkdir(parents=True, exist_ok=True)
    table = folder / "real.csv"
    table.write_text(delimited_text(header, rows), encoding="utf-8", newline="")
    run = cycle(table, flags, seed, generate, validate)
    document = json.loads(run["description"].read_text("utf-8"))
    twin: "list[list[str]]" = []
    if generate:
        twin = list(csv.reader(io.StringIO(run["twin"].read_text("utf-8"), newline="")))
    exits = {k: run[k] for k in ("profile", "generate", "validate_twin", "validate_real")}
    return document, twin, exits


def room_rows(figures: "int | None") -> "list[list[str]]":
    """1,000 REC-prefixed record numbers of ``figures`` figures, or 989 bare ones."""
    if figures is None:
        return [[f"{i:03d}", "group_x"] for i in range(989)]
    return [[f"REC{i:0{figures}d}", "group_x"] for i in range(1000)]


def subject_rows() -> "list[list[str]]":
    """2,000 SUBJ- record numbers beside a 60-value age column."""
    return [[f"SUBJ-{10000 + i}", f"{20 + (i * 7) % 60}"] for i in range(2000)]


# -- the population floor's battery (ledger K-S3-01, plan P4-D341) ------


def visits_table(rows: int, subjects: "int | None" = None) -> str:
    """A repeated-measures table: ``rows`` visits over ``subjects`` people.

    With no subject count every `subject_id` is different, which is a
    column that names a ROW and never a person, so the table's
    population is its rows. The other columns are the two shapes that
    must never be mistaken for people: a set of categories and a
    bounded whole-number scale.
    """
    draw = random.Random(4)
    built: "list[list[str]]" = []
    for place in range(rows):
        who = place if subjects is None else place % subjects
        built += [
            [
                f"P{who + 1:05d}",
                ("north", "south", "east", "west")[place % 4],
                f"{draw.randint(0, 100)}",
            ]
        ]
    return delimited_text(["subject_id", "site", "score"], built)


# Every size and person shape the population floor is measured over:
# (name, rows, subjects or None, whether `subject_id` is declared). The
# sizes sit at both ends of each band and one step outside it, so a
# floor or a notice line that moved would change the counts.
POPULATION_BATTERY = (
    ("one row", 1, None, False),
    ("half a floor", 50, None, False),
    ("one short of the floor", 99, None, False),
    ("at the floor", 100, None, False),
    ("mid band", 500, None, False),
    ("one short of the line", 999, None, False),
    ("at the line", 1000, None, False),
    ("well over the line", 1500, None, False),
    ("people one short of the floor", 500, 99, True),
    ("people at the floor", 500, 100, True),
    ("people in the band", 1200, 300, True),
    ("people over the line", 4000, 1000, True),
    ("a declared identifier that never repeats", 500, None, True),
)


def lone_count_shapes() -> "dict[str, tuple[list[str], list[list[str]], list[str], str, str]]":
    """The three shapes whose one named count of one stands (ledger K-2B-28 and K-2B-48).

    name -> (header, rows, flags, column, the key allowed to hold 1).
    """
    draw = random.Random(8)
    words = ["alpha", "bravo", "delta", "echo", "fox", "golf", "hotel", "india",
             "kilo", "lima", "mike", "oscar", "papa", "romeo", "sierra", "tango"]
    notes: "set[str]" = set()
    while len(notes) < 999:
        notes.add(" ".join(draw.choice(words) for _ in range(8)))
    cells = sorted(notes) + ["42"]
    draw.shuffle(cells)
    free = [[c, "k"] for c in cells]
    pooled = ["NORTH"] * 1977 + ["SOUTH"] * 11 + ["SITE_X"]
    random.Random(3).shuffle(pooled)
    first = datetime.date(2020, 1, 1)
    dates = [(first + datetime.timedelta(days=i)).isoformat() for i in range(118)]
    dates += ["2024-07-01T00:00:00", "unreadable"]
    floor = ["--smallest-group", "11"]
    return {
        "free_text": (["note", "other"], free, floor, "note", "n_numeric"),
        "pooled_labels": (["value", "other"], [[c, "k"] for c in pooled], floor, "value", "n_missing"),
        "dates": (["value", "other"], [[c, "k"] for c in dates], floor, "value", "n_unparsed"),
    }


def ones_in(block: object, path: str = "") -> "list[str]":
    """Every numeric leaf equal to 1 inside a description block, by path."""
    out: "list[str]" = []
    if isinstance(block, dict):
        for key in sorted(block):
            out += ones_in(block[key], f"{path}/{key}")
    elif isinstance(block, list):
        for place, item in enumerate(block):
            out += ones_in(item, f"{path}/{place}")
    elif isinstance(block, int) and not isinstance(block, bool) and block == 1:
        out += [path]
    return out


def autofilter_book(with_filter: bool) -> bytes:
    """A title line, an ambiguous first row of canaries, and 120 records."""
    rows = [(1, [workbooks.cell("A1", "Study overview", "inlineStr")])]
    rows += [(2, [workbooks.cell("A2", "PERSON_CANARY", "inlineStr"),
                  workbooks.cell("B2", "PRIVATE_CANARY", "inlineStr")])]
    for i in range(120):
        n = 3 + i
        rows += [(n, [workbooks.cell(f"A{n}", f"record{i}word", "inlineStr"),
                      workbooks.cell(f"B{n}", f"word{i}record", "inlineStr")])]
    return workbooks.package([
        ("[Content_Types].xml", workbooks._content_types(1, False, False, False)),
        ("_rels/.rels", workbooks._root_rels()),
        ("xl/workbook.xml", workbooks._workbook([("Data", "")])),
        ("xl/_rels/workbook.xml.rels", workbooks._workbook_rels(1, False)),
        ("xl/styles.xml", _plain_styles()),
        ("xl/worksheets/sheet1.xml", workbooks.sheet(
            rows, dimension="A1:B122", autofilter="A2:B122" if with_filter else "")),
    ])


# -- single-column shapes (K-P4-03, K-P4-05, K-P4-17) ---------------------


def dotted_two_figure_dates() -> "list[str]":
    """300 cells like 19.08.24 (tests/test_p4d15_dotted_and_two_digit_dates.py)."""
    return [f"{day:02d}.{month:02d}.24" for day in range(1, 26) for month in range(1, 13)]


def pressure_rows(rows: int = 400) -> "list[str]":
    """A repeating blood pressure: R-P4-40's own shape (tools/measurements/r_p4_40_l7_joined.py)."""
    draw = random.Random(20260903)
    out = []
    for _ in range(rows):
        systolic = draw.choice([100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148])
        diastolic = draw.choice([56, 60, 64, 68, 72, 76, 80, 84, 88])
        out += ["%d/%d" % (systolic, diastolic)]
    return out


def readings_and_markers() -> "list[str]":
    """295 lab readings in 0.1-40.0 and 5 'NOT DETECTED' markers (Random(5))."""
    draw = random.Random(5)
    values = [f"{draw.uniform(0.1, 40.0):.1f}" for _ in range(295)] + ["NOT DETECTED"] * 5
    draw.shuffle(values)
    return values


def gaussian_table(rows: int, columns: int = 4) -> str:
    """``columns`` Gaussian columns at two decimals (K-S1-07)."""
    draw = random.Random(20260913)
    head = [f"m{c:02d}" for c in range(columns)]
    lines = [",".join(head)]
    for _ in range(rows):
        lines += [",".join(f"{draw.gauss(50 + c, 5 + c % 7):.2f}" for c in range(columns))]
    return "\n".join(lines) + "\n"
