"""L6: the three width residuals, measured through the real path.

R-P4-30 (dental codes), R-P4-35 (a fixed-width vaccine code column
whose larger codes need no leading zero) and R-P4-27 (the value stage
that cannot see the fields the census asks for), each built as a CSV,
described by the real producer, loaded by the real loader, generated by
the real generator and checked by the real validator.

Nothing here is stubbed: the only thing this file does that a user does
not is recount the twin's own cells so the shortfall can be printed
next to the published census.
"""
import collections
import pathlib
import random
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests"))
import fixtures  # noqa: E402
from synthtwin import (  # noqa: E402
    contract,
    generation,
    parsing,
    profile,
    reading,
    rendering,
    taxonomy,
    validation,
)


def dental_rows():
    """300 rows of `D` plus four figures, 85 distinct codes, 97 padded."""
    random.seed(20260901)
    padded = ["D0%03d" % n for n in (120, 140, 150, 170, 180, 185, 210, 220,
                                     230, 240, 250, 260, 270, 272, 274, 277,
                                     330, 350, 351, 460, 470, 502, 601, 602,
                                     603, 701, 702, 703, 706, 707, 708)]
    plain = []
    for stem in (1110, 1120, 1206, 1208, 1351, 1354, 2140, 2150, 2160, 2161,
                 2330, 2331, 2332, 2335, 2391, 2392, 2393, 2394, 2740, 2750,
                 2751, 2752, 2790, 2791, 2792, 2910, 2915, 2920, 2929, 2930,
                 2940, 2950, 2951, 2952, 2954, 2960, 3220, 3310, 3320, 3330,
                 4210, 4211, 4240, 4241, 4260, 4261, 4341, 4342, 4355, 4910,
                 5110, 5120, 5211,  5212):
        plain.append("D%04d" % stem)
    rows = []
    for index in range(97):
        rows.append(padded[index % len(padded)])
    for index in range(203):
        rows.append(plain[index % len(plain)])
    random.shuffle(rows)
    return rows


def vaccine_rows():
    """230 rows of a `000`-`199` code column: 127 padded, 103 not."""
    random.seed(20260902)
    rows = ["%03d" % (n % 100) for n in range(127)]
    rows = rows + ["%03d" % (100 + (n % 100)) for n in range(103)]
    random.shuffle(rows)
    return rows


def signed_rows():
    """R-P4-27's column: eleven `+1`, eleven `-99`, eleven `-02`."""
    return ["+1"] * 11 + ["-99"] * 11 + ["-02"] * 11


def describe(home, stem, rows, header="code"):
    fixtures.write(home, f"{stem}.csv", header + "\n" + "\n".join(rows) + "\n")
    table = reading.read_table(
        str(home / f"{stem}.csv"), first_row=reading.FIRST_ROW_AUTOMATIC
    )
    document = profile.build_document(table, taxonomy.Settings(), [])
    loaded = contract.load_profile(
        str(fixtures.write_profile(home, f"{stem}-p.json", document))
    )
    return document, loaded


def widths_of(cells, affix=False):
    """Recount the field width of every whole-number cell written."""
    tally = collections.Counter()
    styles = collections.Counter()
    for cell in cells:
        text = cell
        if affix:
            text = text[1:] if text[:1] == "D" else text
        if parsing.classify_number(text) != parsing.NUMBER:
            continue
        if "." in text:
            continue
        tally[parsing.pad_width(text)] += 1
        styles[parsing.numeric_style(text)] += 1
    return tally, styles


def block_of(document, name):
    for column in document["columns"]:
        if column["name"] == name:
            return column
    raise KeyError(name)


def run(stem, rows, header, affix, seeds=(3, 11, 29)):
    print(f"\n===== {stem} =====")
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        document, loaded = describe(home, stem, rows, header)
        block = block_of(document, header)
        source = block
        if affix:
            source = block
        print("role:", block["role"])
        for key in ("numeric_styles", "pad_widths", "fraction_widths",
                    "field_widths"):
            if key in source:
                print(f"published {key}:", source[key])
        published, published_styles = widths_of(rows, affix)
        print("source recount, width -> cells:", dict(sorted(published.items())))
        print("source recount, style -> cells:", dict(sorted(published_styles.items())))
        for seed in seeds:
            twin = generation.generate(loaded, seed)
            path = fixtures.write(
                home, f"{stem}-{seed}.csv", rendering.twin_csv(twin)
            )
            cells = [line for line in
                     path.read_text(encoding="utf-8").splitlines()[1:] if line]
            got, got_styles = widths_of(cells, affix)
            report = validation.measure(loaded, str(path))
            missed = [
                f"{check.fact} {check.verdict} {check.published} -> {check.achieved}"
                for check in report.checks
                if check.verdict not in ("HELD", "WITHIN-BOUND",
                                         "AUTHORIZED-DEVIATION", "NOT-CHECKABLE",
                                         "WITHHELD", "LISTED")
            ]
            print(f"  seed {seed}: twin width -> cells:",
                  dict(sorted(got.items())),
                  " style -> cells:", dict(sorted(got_styles.items())))
            for line in missed:
                print("    validator:", line)


if __name__ == "__main__":
    run("dental", dental_rows(), "code", True)
    run("vaccine", vaccine_rows(), "code", False)
    run("signed", signed_rows(), "reading", False)
