"""L7: the joined role's distinct counts, measured through the real path.

R-P4-40 (a joined column's positions repeat more evenly than the real
ones did), R-P4-112 (a joined position is laid out by the CELL count),
R-P4-71 (the role cannot hold the all-different obligation), R-P4-51 (a
three-position column reproduces only the pairs its last position is
in) and R-P4-20 (how many different NUMBERS the twin holds), each built
as a CSV, described by the real producer, loaded by the real loader,
generated by the real generator and checked by the real validator.

Nothing here is stubbed: the only thing this file does that a user does
not is recount the twin's own cells so a shortfall can be printed next
to the published count.
"""
import collections
import pathlib
import random
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests"))
import fixtures  # noqa: E402
from synthtwin import (  # noqa: E402
    contract,
    generation,
    parsing,
    profile,
    reading,
    rendering,
    taxonomy,
    validation,
)

# FORTY SEEDS, AND TEN UNTIL REVIEW ROUND 1 (item 4). Ten gave the
# OPPOSITE direction to forty on residual R-P4-122 -- 6 seeds short
# against 8, where forty says 30 against 28 -- so every comparison this
# file makes is taken at the scope that settled that one.
SEEDS = tuple(range(40))


def witness_rows():
    """R-P4-112's own 36-row column: 11 first numbers, 7 second ones."""
    return [
        "%d/%d" % (index % 9 + 1, index % 7 + 1) for index in range(34)
    ] + ["1.5/2", "2.5/3"]


def pressure_rows(rows=400):
    """A repeating blood pressure: R-P4-40's own shape."""
    random.seed(20260903)
    out = []
    for _ in range(rows):
        systolic = random.choice([100, 104, 108, 112, 116, 120, 124, 128,
                                  132, 136, 140, 144, 148])
        diastolic = random.choice([56, 60, 64, 68, 72, 76, 80, 84, 88])
        out.append("%d/%d" % (systolic, diastolic))
    return out


def r_p4_40_own_column(rows=400):
    """R-P4-40's own shape: 400 readings publishing ~324 different cells.

    The residual was opened on a column of this size and spread, whose
    twin reached 276 of 324 while the walk was free to chase the count.
    """
    random.seed(20260905)
    out = []
    for _ in range(rows):
        systolic = random.randint(95, 165)
        diastolic = random.randint(50, 100)
        out.append("%d/%d" % (systolic, diastolic))
    return out


def value_counts(seeds=SEEDS):
    """Does a PLAIN column hold as many different numbers as published?

    `n_distinct_values` is REPORT-ONLY (plan P4-D4.9), and landing L7
    makes it drive the layout of every grain inside a role. Whether it
    could become EXACT-OBSERVABLE is a question about whether the twin
    MEETS it, which is measured here rather than preferred.
    """
    print("\n===== n_distinct_values, published against held =====")
    random.seed(20260906)
    shapes = [
        ("tight cluster", [
            "%0.2f" % (10 + random.random()) for _ in range(200)
        ]),
        ("whole numbers", [
            "%d" % random.randint(1, 40) for _ in range(200)
        ]),
        ("wide spread", [
            "%d" % random.randint(1, 5000) for _ in range(200)
        ]),
        ("few values", [
            "%d" % (index % 7) for index in range(200)
        ]),
    ]
    met = 0
    runs = 0
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        for stem, rows in shapes:
            path = fixtures.write(
                home, f"{stem}.csv".replace(" ", "-"),
                fixtures.single_column_table("amount", rows),
            )
            table = reading.read_table(str(path))
            document = profile.build_document(
                table, taxonomy.Settings(), [], None, None
            )
            loaded = contract.load_profile(str(fixtures.write_profile(
                home, f"{stem}-p.json".replace(" ", "-"), document
            )))
            column = loaded.columns[0]
            published = column.facts.n_distinct_values
            held = []
            for seed in seeds:
                twin = generation.generate(loaded, seed)
                numbers = set()
                for cell in twin.columns[0]:
                    if cell == "":
                        continue
                    numbers.add(parsing.exact_of_spelling(cell))
                held.append(len(numbers))
                runs = runs + 1
                if len(numbers) == published:
                    met = met + 1
            print(f"  {stem}: published {published}, held {held}")
    print(f"  met exactly: {met} of {runs} runs")


def grain_counts(seeds=SEEDS):
    """What the grain rule costs an ALL-DIFFERENT joined column.

    Retargeting the layout is right for a column whose cells repeat and
    it takes something from one whose cells are all different, because
    the count it replaces -- the whole cell's -- happened to equal the
    number of CELLS there, so every position got one stratum per cell.
    Both directions are printed here rather than only the one that
    improves.
    """
    print("\n===== the grain rule on repeating and all-different columns =====")
    shapes = [
        ("repeating (110 of 400 cells)", pressure_rows()),
        ("all different (240 of 240)", all_different_rows()),
        ("all different (379 of 400)", r_p4_40_own_column()),
    ]
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        for stem, rows in shapes:
            key = stem.split(" ")[0]
            _document, loaded = describe(home, f"grain-{key}", rows)
            column = loaded.columns[0]
            facts = column.facts
            cells = []
            held = collections.defaultdict(list)
            for seed in seeds:
                twin = generation.generate(loaded, seed)
                written = [cell for cell in twin.columns[0] if cell != ""]
                cells.append(len(set(written)))
                for place in range(facts.n_parts):
                    spelt = numbers_of(written, facts.separator, place)
                    held[place].append(len({
                        parsing.exact_of_spelling(one) for one in spelt
                    }))
            print(f"  {stem}")
            print(f"    cells: published {column.n_distinct}, "
                  f"held {min(cells)}-{max(cells)}")
            for place in range(facts.n_parts):
                published = facts.parts[place].n_distinct_values
                print(f"    position {place + 1} numbers: published "
                      f"{published}, held {min(held[place])}"
                      f"-{max(held[place])}")


def all_different_rows(rows=240):
    """Every cell different: R-P4-71's obligation."""
    out = []
    for index in range(rows):
        out.append("%d/%d" % (100 + index // 12, 50 + index % 12))
    return out


def three_position_rows():
    """R-P4-51's column: positions 1 and 2 perfectly anti-correlated."""
    out = []
    for _ in range(25):
        out = out + ["1/4/10", "2/3/20", "3/2/30", "4/1/40"]
    return out


def describe(home, stem, rows, header="reading"):
    fixtures.write(home, f"{stem}.csv", header + "\n" + "\n".join(rows) + "\n")
    table = reading.read_table(
        str(home / f"{stem}.csv"), first_row=reading.FIRST_ROW_AUTOMATIC
    )
    document = profile.build_document(
        table, taxonomy.Settings(), [], None, [header]
    )
    loaded = contract.load_profile(
        str(fixtures.write_profile(home, f"{stem}-p.json", document))
    )
    return document, loaded


def numbers_of(cells, separator, place):
    """Every number one position of the twin actually wrote."""
    out = []
    for cell in cells:
        if cell == "":
            continue
        pieces = cell.split(separator)
        if len(pieces) <= place:
            continue
        one = parsing.parse_number(pieces[place])
        if one is not None:
            out.append(pieces[place])
    return out


def run(stem, rows, header="reading", seeds=SEEDS, show_pairs=False):
    print(f"\n===== {stem} =====")
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        document, loaded = describe(home, stem, rows, header)
        column = loaded.columns[0]
        print("role:", column.role, " rows:", column.n_present)
        facts = column.facts
        if not isinstance(facts, contract.JoinedFacts):
            print("NOT JOINED -- nothing below is about this residual")
            return
        print("published n_distinct (cells):", column.n_distinct,
              " n_distinct_folded:", column.n_distinct_folded)
        for place in range(facts.n_parts):
            part = facts.parts[place]
            print(f"  position {place + 1}: n_distinct_values="
                  f"{part.n_distinct_values}"
                  f" styles={part.numeric_styles}")
        print("  part_agreements:", facts.part_agreements,
              " part_above:", facts.part_above)
        held_cells = []
        held_values = collections.defaultdict(list)
        strata = []
        for place in range(facts.n_parts):
            view = generation._part_view(column, place)
            layout, _notes, _content = generation._numeric_layout(
                view, facts.parts[place],
                facts.parts[place].n_distinct_values,
            )
            strata.append(len(layout.sizes))
        print("  strata per position:", strata)
        missed_tally = collections.Counter()
        for seed in seeds:
            twin = generation.generate(loaded, seed)
            cells = [cell for cell in twin.columns[0] if cell != ""]
            held_cells.append(len(set(cells)))
            for place in range(facts.n_parts):
                spelt = numbers_of(cells, facts.separator, place)
                held_values[place].append(
                    len({parsing.exact_of_spelling(one) for one in spelt})
                )
            home_seed = home / f"{stem}-{seed}"
            home_seed.mkdir(exist_ok=True)
            written = fixtures.write(
                home_seed, "twin.csv", rendering.twin_csv(twin)
            )
            outcome = validation.measure(loaded, str(written))
            for check in outcome.checks:
                if check.verdict == validation.MISSED:
                    missed_tally[check.subcheck] += 1
        print("  twin distinct CELLS over seeds:", held_cells,
              f" (published {column.n_distinct})")
        for place in range(facts.n_parts):
            print(f"  twin distinct NUMBERS position {place + 1}:",
                  held_values[place],
                  f" (published {facts.parts[place].n_distinct_values})")
        print("  validator MISSED subchecks, seeds out of", len(seeds), ":")
        for name in sorted(missed_tally):
            print(f"    {missed_tally[name]:3d}  {name}")
        if not missed_tally:
            print("    (none)")


def battery(seeds=SEEDS):
    """Every pair of a three- and four-position column, against G12.9.

    R-P4-51's own column is one shape. This walks a battery of columns
    of three and four positions, built to pull their pairs against each
    other, and prints how far every pair lands from its published value
    -- so "every pair is aimed at" is a measurement and not a claim
    read off the code.
    """
    print("\n===== the pairs of a three- and four-position battery =====")
    random.seed(20260904)
    shapes = []
    for case in range(12):
        rows = []
        parts = 3 + case % 2
        for _ in range(150):
            first = random.randint(10, 60)
            second = first + random.randint(-8, 8)
            third = random.randint(1, 40)
            fourth = 100 - first
            held = [first, second, third, fourth][:parts]
            rows.append("/".join(str(one) for one in held))
        shapes.append((f"battery-{case}", rows))
    worst = 0.0
    worst_where = ""
    above_missed = 0
    pairs_seen = 0
    outside = 0
    early_pairs = 0
    early_outside = 0
    early_above_missed = 0
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        for stem, rows in shapes:
            _document, loaded = describe(home, stem, rows)
            column = loaded.columns[0]
            facts = column.facts
            if not isinstance(facts, contract.JoinedFacts):
                print(f"  {stem}: role {column.role}, skipped")
                continue
            for seed in seeds:
                twin = generation.generate(loaded, seed)
                cells = [cell for cell in twin.columns[0] if cell != ""]
                held = []
                for place in range(facts.n_parts):
                    held.append([
                        float(one)
                        for one in numbers_of(cells, facts.separator, place)
                    ])
                seat = 0
                for first in range(facts.n_parts):
                    for second in range(first + 1, facts.n_parts):
                        got = generation._rank_agreement(
                            held[first], held[second]
                        )
                        gap = abs(
                            round(got, 4) - facts.part_agreements[seat]
                        )
                        pairs_seen = pairs_seen + 1
                        early = second != facts.n_parts - 1
                        if early:
                            early_pairs = early_pairs + 1
                        if gap > 0.02:
                            outside = outside + 1
                            if early:
                                early_outside = early_outside + 1
                        if gap > worst:
                            worst = gap
                            worst_where = f"{stem} seed {seed} pair {seat}"
                        rows_above = 0
                        for row in range(len(held[first])):
                            if held[first][row] > held[second][row]:
                                rows_above = rows_above + 1
                        if rows_above != facts.part_above[seat]:
                            above_missed = above_missed + 1
                            if early:
                                early_above_missed = early_above_missed + 1
                        seat = seat + 1
    print(f"  pairs measured: {pairs_seen}")
    print(f"  widest agreement gap: {worst:.4f} at {worst_where}"
          f"  (G12.9 window 0.02)")
    print(f"  agreements outside the 0.02 window: {outside} of {pairs_seen}")
    print(f"  above-counts missed: {above_missed} of {pairs_seen}")
    print(f"  pairs between two EARLIER positions: {early_pairs}"
          f"  -- {early_outside} outside the window,"
          f" {early_above_missed} above-counts missed")


def main():
    run("r_p4_112_witness", witness_rows())
    run("r_p4_40_pressure", pressure_rows())
    run("r_p4_71_all_different", all_different_rows())
    run("r_p4_51_three_positions", three_position_rows(), show_pairs=True)
    run("r_p4_40_own_column", r_p4_40_own_column())
    battery()
    value_counts()
    grain_counts()


if __name__ == "__main__":
    main()
