"""L8: values where the description says there are none.

R-P4-136 (a twin puts cells in a stretch the real column left empty),
R-P4-138 (the fact's resolution is one bin, so cells stay inside the
source's TRUE gap), R-P4-139 (two-cluster columns miss
`widths.published.1` at every seed, before this landing and after it)
and R-P4-140 (what the class REPORT-ONLY was decided on), each built as
a CSV, described by the real producer, loaded by the real loader,
generated by the real generator and checked by the real validator.

**Run it with the tree to measure as its first argument**, so the SAME
file measures the tree before this landing and the tree after it. That
is how the before column of every table here was taken: a second
worktree at the commit this branched from, its own virtual environment,
and this file handed its path. The bins are computed HERE from the
source rows with `parsing.histogram_bin`, which both trees ship, so the
before run needs no key the before tree does not publish.

Nothing here is stubbed: the only thing this file does that a user does
not is recount the twin's own cells so a leak can be printed next to
the stretch it is in.
"""
import collections
import pathlib
import random
import sys
import tempfile

ROOT = pathlib.Path(
    sys.argv[1] if len(sys.argv) > 1
    else pathlib.Path(__file__).resolve().parents[2]
)
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests"))
import fixtures  # noqa: E402
from synthtwin import (  # noqa: E402
    contract, generation, parsing, profile, reading, taxonomy,
    validation,
)

SEEDS = tuple(range(40))


def two_tight():
    r = random.Random(11)
    return ([f"{round(r.gauss(20, 2), 1)}" for _ in range(150)]
            + [f"{round(r.gauss(80, 3), 1)}" for _ in range(150)])


def uneven():
    r = random.Random(12)
    return ([f"{round(r.gauss(10, 2), 1)}" for _ in range(250)]
            + [f"{round(r.gauss(90, 3), 1)}" for _ in range(50)])


def closer():
    r = random.Random(13)
    return ([f"{round(r.gauss(40, 2), 1)}" for _ in range(150)]
            + [f"{round(r.gauss(60, 3), 1)}" for _ in range(150)])


SHAPES = (
    ("two tight peaks", two_tight),
    ("uneven", uneven),
    ("peaks closer", closer),
)


def describe(home, stem, rows, floor=1, header="amount"):
    fixtures.write(home, f"{stem}.csv", header + "\n" + "\n".join(rows) + "\n")
    table = reading.read_table(
        str(home / f"{stem}.csv"), first_row=reading.FIRST_ROW_AUTOMATIC
    )
    document = profile.build_document(
        table, taxonomy.Settings(small_cell_floor=floor), [], None, [header]
    )
    loaded = contract.load_profile(
        str(fixtures.write_profile(home, f"{stem}-p.json", document))
    )
    return document, loaded


def empty_of(rows):
    """The bins the SOURCE leaves empty, by the shipped bin rule."""
    numbers = [float(one) for one in rows]
    low, high = min(numbers), max(numbers)
    held = {parsing.histogram_bin(one, low, high) for one in numbers}
    return (low, high,
            [b for b in range(parsing.HISTOGRAM_BINS) if b not in held])


def true_gap(rows):
    """The widest stretch the source holds nothing in."""
    numbers = sorted(float(one) for one in rows)
    widest = (0.0, 0.0, 0.0)
    for low, high in zip(numbers, numbers[1:]):
        if high - low > widest[0]:
            widest = (high - low, low, high)
    return widest[1], widest[2]


def leaks(twin, low, high, barred, gap):
    into_bin = 0
    into_gap = 0
    deepest = 0.0
    for cell in twin.columns[0]:
        if cell == "":
            continue
        value = parsing.parse_number(cell)
        if value is None:
            continue
        if parsing.histogram_bin(value, low, high) in barred:
            into_bin = into_bin + 1
        if gap[0] < value < gap[1]:
            into_gap = into_gap + 1
            reach = min(value - gap[0], gap[1] - value)
            if reach > deepest:
                deepest = reach
    return into_bin, into_gap, deepest


def the_three(floor=1):
    print(f"\n===== the three shapes at floor {floor}, {len(SEEDS)} seeds =====")
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        for name, build in SHAPES:
            rows = build()
            low, high, barred = empty_of(rows)
            gap = true_gap(rows)
            _document, loaded = describe(
                home, name.replace(" ", "-"), rows, floor
            )
            hist = loaded.columns[0].facts.value_histogram
            bins, gaps, deep = [], [], []
            for seed in SEEDS:
                twin = generation.generate(loaded, seed)
                one, two, three = leaks(twin, low, high, set(barred), gap)
                bins.append(one)
                gaps.append(two)
                deep.append(three)
            print(f"  {name}: source gap {gap[0]} .. {gap[1]}; "
                  f"{len(barred)} empty bins; census "
                  f"{'published ' + str(len(hist)) + ' bins' if hist else 'WITHHELD'}")
            print(f"    cells in a bin the source leaves EMPTY: "
                  f"{min(bins)}-{max(bins)}, mean {sum(bins)/len(bins):.2f} "
                  f"of {len(rows)}")
            print(f"    cells inside the source's own gap:       "
                  f"{min(gaps)}-{max(gaps)}, mean {sum(gaps)/len(gaps):.2f}")
            print(f"    furthest such cell from a real value:    "
                  f"{min(deep):.2f}-{max(deep):.2f} "
                  f"(the gap is {gap[1]-gap[0]:.2f} wide)")


def obligations():
    """What `synthtwin validate` says about a twin of each shape."""
    print(f"\n===== the quality report on each twin, {len(SEEDS)} seeds =====")
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        for name, build in SHAPES:
            rows = build()
            _document, loaded = describe(
                home, name.replace(" ", "-"), rows
            )
            missed = collections.Counter()
            clean = 0
            for seed in SEEDS:
                twin = generation.generate(loaded, seed)
                path = home / f"{name.replace(' ', '-')}-{seed}.csv"
                fixtures.write(
                    home, path.name,
                    fixtures.rows_to_csv(
                        list(twin.names),
                        [list(row) for row in twin.rows],
                    ),
                )
                outcome = validation.measure(loaded, f"{path}")
                names = [
                    check.subcheck or check.fact
                    for check in outcome.checks
                    if check.verdict == validation.MISSED
                ]
                if not names:
                    clean = clean + 1
                for one in names:
                    missed[one] = missed[one] + 1
            print(f"  {name}: {clean} of {len(SEEDS)} seeds missed nothing")
            for one, count in sorted(missed.items()):
                print(f"      {one}: missed at {count} seed(s)")


def battery():
    """Does the pass ever leave a cell where a description says none is?

    Forty described columns, forty seeds each, over shapes that are not
    the three this landing was built on: whole numbers, negatives,
    columns spanning zero, tiny ranges, one big outlier, and columns
    with no empty bin at all.
    """
    print(f"\n===== forty columns, {len(SEEDS)} seeds each =====")
    random.seed(20260901)
    shapes = []
    # TWO HUNDRED CELLS EACH, and the documents that quote this
    # battery say so now. They said three hundred until 2026-09-04
    # (review round 5 item 2); the battery is left at the size it was
    # measured at, because the figure it is compared against -- 119 of
    # 1600, taken before the stretch edges landed -- was taken on
    # exactly these columns.
    for index in range(10):
        gap = 20 + index * 5
        shapes.append((f"whole two peaks {index}", [
            f"{random.randint(1, 20)}" if step % 2 else f"{random.randint(gap, gap + 20)}"
            for step in range(200)
        ]))
    for index in range(10):
        shapes.append((f"across zero {index}", [
            f"{round(random.gauss(-50 - index, 3), 2)}" for _ in range(100)
        ] + [
            f"{round(random.gauss(50 + index, 3), 2)}" for _ in range(100)
        ]))
    for index in range(10):
        shapes.append((f"one outlier {index}", [
            f"{round(random.gauss(10, 1), 3)}" for _ in range(199)
        ] + [f"{1000 + index * 100}"]))
    for index in range(10):
        shapes.append((f"no gap {index}", [
            f"{round(random.uniform(0, 100), 2)}" for _ in range(200)
        ]))
    runs = 0
    leaked = 0
    worst = 0
    withgap = 0
    noted = 0
    in_pair = 0
    worst_pair = 0
    in_gap = 0
    worst_gap = 0
    with tempfile.TemporaryDirectory() as folder:
        home = pathlib.Path(folder)
        for stem, rows in shapes:
            low, high, barred = empty_of(rows)
            if barred:
                withgap = withgap + 1
            try:
                _document, loaded = describe(
                    home, stem.replace(" ", "-"), rows
                )
            except Exception as trouble:      # noqa: BLE001
                print(f"  {stem}: DECLINED -- {type(trouble).__name__}")
                continue
            if not isinstance(loaded.columns[0].facts, contract.NumericFacts):
                print(f"  {stem}: role {loaded.columns[0].role}, skipped")
                continue
            mine = 0
            myworst = 0
            mynotes = 0
            # THE SOURCE'S OWN WIDEST GAP, computed from the rows and
            # not from any published key, so the same quantity can be
            # counted on a tree that has no `empty_edges` at all. It is
            # what residual R-P4-138 is about and what the bins alone
            # cannot answer.
            gap = true_gap(rows)
            for seed in SEEDS:
                twin = generation.generate(loaded, seed)
                one, two, _three = leaks(
                    twin, low, high, set(barred), gap
                )
                if two:
                    in_gap = in_gap + 1
                    worst_gap = max(worst_gap, two)
                # ...AND INSIDE ANY PUBLISHED PAIR, which the bins
                # alone do not answer (residual R-P4-138, plan
                # P4-D35). A bin is coarser than a gap, so a cell can
                # sit inside the stretch the description names and in
                # a bin that holds plenty; counting bins alone reports
                # a rate for the coarser key only.
                inside = 0
                for cell in twin.columns[0]:
                    if cell == "":
                        continue
                    value = parsing.parse_number(cell)
                    if value is None:
                        continue
                    for pair in loaded.columns[0].facts.empty_edges:
                        if pair[0] < value < pair[1]:
                            inside = inside + 1
                            break
                runs = runs + 1
                if one:
                    leaked = leaked + 1
                    mine = mine + 1
                    worst = max(worst, one)
                    myworst = max(myworst, one)
                if inside:
                    in_pair = in_pair + 1
                    worst_pair = max(worst_pair, inside)
                for note in twin.deviations:
                    if note.fact in ("empty_bins", "empty_edges"):
                        noted = noted + 1
                        mynotes = mynotes + 1
            if mine:
                facts = loaded.columns[0].facts
                print(f"    {stem}: {mine}/{len(SEEDS)} runs leak, worst "
                      f"{myworst} cell(s), {mynotes} note(s); "
                      f"{len(barred)} empty bins, integer_valued "
                      f"{facts.integer_valued}, "
                      f"ends {facts.percentiles.minimum}..{facts.percentiles.maximum}")
    print(f"  {len(shapes)} columns, {withgap} of them with an empty bin")
    print(f"  runs: {runs}; runs leaving a cell in an empty bin: {leaked}; "
          f"worst run: {worst} cell(s)")
    print(f"  runs leaving a cell inside a PUBLISHED PAIR: {in_pair}; "
          f"worst run: {worst_pair} cell(s)")
    print(f"  runs leaving a cell inside the SOURCE's own widest gap: "
          f"{in_gap}; worst run: {worst_gap} cell(s)")
    print(f"  deviations naming a gap key: {noted}")


if __name__ == "__main__":
    the_three(1)
    the_three(11)
    obligations()
    battery()
