"""How long each test file takes, for packing the CI shards.

MEASURED, NOT GUESSED. Every number below is one file's own share of a
single ordinary `pytest -q --durations=0` run of the whole suite on the
reference machine the KPI ledger names (Apple M4, ten cores): the
setup, call and teardown seconds of its cases, added up. That is the
cost a shard inherits when it takes the file, its module-scoped
fixtures included. Interpreter start and collection are left out: a
shard is charged for those once, however many files it holds.

TO RE-MEASURE, on a quiet reference machine:

    .venv/bin/python -m pytest -q --durations=0 > durations.txt

and add up, per file, the seconds it prints against each case.

WHAT A STALE NUMBER COSTS, AND WHAT IT CANNOT COST. These seconds
decide only the PACKING: which shard a file lands in. A number that has
drifted makes one shard longer than another and never makes a file run
twice or not at all -- `tools/ci/shards.py --prove` is what holds that,
against pytest's own collection. So this table is a convenience that
may be re-measured whenever somebody wants the shards to come out
closer in length, and it is never a thing a test result depends on.

A FILE WITH NO ROW weighs `DEFAULT_SECONDS`. Two kinds of file have
none: one added since the last measurement, which is then placed like
an ordinary small file and runs in its shard from the commit that adds
it; and one every case of which fell under the five milliseconds pytest
prints a duration for at all, which is a file the default overstates
and which costs the packing nothing worth another decimal.
"""

# The weight of a test file this table has no measurement for: a little
# over the median file, so a handful of new files cannot all land in one
# shard by looking free.
DEFAULT_SECONDS = 2.0

SECONDS = {
    "tests/test_ap311_lowered_floor.py": 7.63,
    "tests/test_ap312_fold_repair.py": 103.43,
    "tests/test_ap313_stated_limit.py": 0.36,
    "tests/test_ap326_unrebuildable_reading_rule.py": 1.61,
    "tests/test_ap329_reading_rule_from_version_5.py": 1.72,
    "tests/test_carried_numbers.py": 5.14,
    "tests/test_ci_shards.py": 0.01,
    "tests/test_claim_inventory.py": 11.68,
    "tests/test_cli_generate.py": 1.21,
    "tests/test_cli_profile.py": 4.38,
    "tests/test_cli_validate.py": 3.66,
    "tests/test_column_analysis.py": 6.62,
    "tests/test_column_analysis_extra.py": 0.17,
    "tests/test_commonest_width_grid.py": 1.49,
    "tests/test_contract_loader.py": 2.46,
    "tests/test_contract_self_check.py": 1.14,
    "tests/test_date_spread.py": 23.86,
    "tests/test_dates_written_forms_disclosed.py": 6.12,
    "tests/test_decontamination.py": 245.96,
    "tests/test_description_line_endings.py": 5.78,
    "tests/test_extra_review_dates.py": 2.29,
    "tests/test_extra_round_disclosure.py": 12.59,
    "tests/test_extra_round_numbers.py": 3.09,
    "tests/test_failure_catalog.py": 0.53,
    "tests/test_file_dialect_round_trip.py": 25.4,
    "tests/test_files_review_2026_09_18.py": 2.59,
    "tests/test_files_review_repairs.py": 4.42,
    "tests/test_final_review_labels.py": 16.94,
    "tests/test_final_skeptic_repairs.py": 11.0,
    "tests/test_generation.py": 4.03,
    "tests/test_generation_reference.py": 6.44,
    "tests/test_held_unit_search.py": 14.53,
    "tests/test_joined_battery_readings.py": 33.86,
    "tests/test_joined_pair_round_trip.py": 33.71,
    "tests/test_k_p3_03_outer_tail_spread.py": 29.41,
    "tests/test_kpi_ledger.py": 57.88,
    "tests/test_kpi_ledger_integrity.py": 3.36,
    "tests/test_landing_2b12_identifiers_codes_text.py": 6.45,
    "tests/test_landing_2b13_numbers_beside_labels.py": 2.72,
    "tests/test_landing_2b15_unanchored_numbers.py": 4.44,
    "tests/test_landing_2b16_number_readings.py": 26.66,
    "tests/test_landing_2b18_forms_and_spellings.py": 27.55,
    "tests/test_landing_2b18_identifier_layout.py": 45.37,
    "tests/test_landing_2b18_layout_disclosure.py": 24.37,
    "tests/test_landing_2b2_number_spellings.py": 25.46,
    "tests/test_landing_2b7_mixed_spellings.py": 7.86,
    "tests/test_landing_2b7_source_spellings.py": 18.65,
    "tests/test_landing_2b8_labels_text_missing.py": 45.42,
    "tests/test_lone_figure_nought.py": 0.1,
    "tests/test_merge_close_2026_09_18.py": 3.88,
    "tests/test_method_citations_resolve.py": 0.19,
    "tests/test_moment_window_anchor.py": 6.19,
    "tests/test_no_quadratic_list_growth.py": 0.48,
    "tests/test_number_censuses_name_no_row.py": 12.5,
    "tests/test_numbers_beside_labels.py": 20.97,
    "tests/test_numeric_strata_round_trip.py": 133.39,
    "tests/test_offline_scan.py": 2.63,
    "tests/test_older_censuses_name_no_row.py": 7.13,
    "tests/test_oracle_proof_layer.py": 0.26,
    "tests/test_oracle_rule_witnesses.py": 5.04,
    "tests/test_p1r6f11_display_boundary.py": 0.11,
    "tests/test_p1r6f4_comprehension_scopes.py": 2.62,
    "tests/test_p1r6f6_first_row_decision.py": 0.08,
    "tests/test_p1r6f7_one_policy.py": 8.55,
    "tests/test_p1r6f8_identifier_evidence.py": 3.09,
    "tests/test_p1r6f9_declared_values.py": 0.67,
    "tests/test_p1r7f1_any_exception.py": 0.02,
    "tests/test_p1r7f1_transaction_disclosure.py": 0.02,
    "tests/test_p1r7f2_declaration_disclosure.py": 0.26,
    "tests/test_p1r7f2_disclosure_is_true.py": 0.61,
    "tests/test_p1r7f2_withholding_block.py": 0.42,
    "tests/test_p1r7f3_exact_declarations.py": 1.5,
    "tests/test_p1r8f1_guard_seam.py": 1.25,
    "tests/test_p1r8f1_working_name_claim.py": 0.83,
    "tests/test_p1r8f2_exact_sentinels.py": 0.79,
    "tests/test_p1r8f4_repetition_multiset.py": 0.08,
    "tests/test_p2c1f2_invention_domain.py": 0.16,
    "tests/test_p2c1f3_publication_guard.py": 8.26,
    "tests/test_p2c1f4_approximation_bounds.py": 2.03,
    "tests/test_p2c1f5_leading_zero_family.py": 69.76,
    "tests/test_p2c1f6_temporal_round_trip.py": 0.24,
    "tests/test_p2c1f8_specification_agreement.py": 0.16,
    "tests/test_p2c2f1_complete_allocation.py": 61.11,
    "tests/test_p2c2f2_style_placement.py": 0.09,
    "tests/test_p2c2f3_style_invention.py": 0.12,
    "tests/test_p2c2f4_numeric_cardinality_bounds.py": 0.09,
    "tests/test_p2c2f5_temporal_endpoints.py": 0.77,
    "tests/test_p2c2f6_fold_collisions.py": 0.04,
    "tests/test_p2c2f8_invention_walk_bound.py": 0.02,
    "tests/test_p2c3f1_published_margins.py": 4.04,
    "tests/test_p2c4f1_disposition_registry.py": 5.14,
    "tests/test_p2c4f2_text_shape.py": 21.28,
    "tests/test_p2c4f3_style_capacity.py": 21.01,
    "tests/test_p2c5f2_identifier_classes.py": 128.88,
    "tests/test_p2c5f3_style_reach.py": 38.58,
    "tests/test_p2c5f4_generation_refusals.py": 1.67,
    "tests/test_p2d10_artifact_words.py": 0.01,
    "tests/test_p3_flip_migration.py": 0.21,
    "tests/test_p3v10f3_the_walk_stops_at_the_tables_keys.py": 0.03,
    "tests/test_p3v10f4_named_markers_are_holes.py": 0.5,
    "tests/test_p3v10f5_exact_equality_wins.py": 7.5,
    "tests/test_p3v11f2_no_refusal_quotes_your_spelling.py": 0.07,
    "tests/test_p3v12f2_a_miss_says_what_it_found.py": 12.65,
    "tests/test_p3v1f12_one_target_transaction.py": 0.98,
    "tests/test_p3v1f2_entry_table.py": 280.55,
    "tests/test_p3v2a1_presence_split.py": 763.75,
    "tests/test_p3v3f1_description_equivalence.py": 19.13,
    "tests/test_p3v3f3_refused_files.py": 0.91,
    "tests/test_p3v3f4_ordinal_spaces.py": 0.3,
    "tests/test_p3v3f5_written_form.py": 0.58,
    "tests/test_p3v3f6_reader_agreement.py": 3.77,
    "tests/test_p3v4f10_windows_reach.py": 1.62,
    "tests/test_p3v4f1_kept_values.py": 31.69,
    "tests/test_p3v4f2_canonical_ceiling.py": 1.04,
    "tests/test_p3v4f3_refusal_equivalence.py": 0.32,
    "tests/test_p3v4f4_datetime_windows.py": 0.69,
    "tests/test_p3v5f1_floor_one.py": 7.17,
    "tests/test_p3v6f1_identifier_corner.py": 0.27,
    "tests/test_p3v7f1_escaped_declarations.py": 0.51,
    "tests/test_p3v7f2_corner_parity.py": 10.06,
    "tests/test_p3v8f5_published_keys.py": 12.04,
    "tests/test_p3v9f1_declared_words_disclosed.py": 0.08,
    "tests/test_p3v9f2_one_key_space.py": 0.08,
    "tests/test_p3v9f3_escaping_is_display_only.py": 0.2,
    "tests/test_p3v9f4_declarations_not_keys.py": 0.29,
    "tests/test_p3v9f5_sentinels_settle.py": 0.25,
    "tests/test_p3v9f6_migration_names_every_option.py": 0.13,
    "tests/test_p3v9f7_declarations_not_keystrokes.py": 0.14,
    "tests/test_p4a1_calendar_placeholders.py": 1.49,
    "tests/test_p4a58_asking_shapes.py": 1.24,
    "tests/test_p4a60_answers_handed_back.py": 0.86,
    "tests/test_p4d140_number_censuses.py": 40.66,
    "tests/test_p4d14_pad_widths.py": 1.0,
    "tests/test_p4d15_dotted_and_two_digit_dates.py": 1.18,
    "tests/test_p4d15_textual_dates.py": 0.38,
    "tests/test_p4d16_padded_numbers.py": 0.26,
    "tests/test_p4d17_group_commas.py": 1.13,
    "tests/test_p4d182_layout_packing.py": 2.74,
    "tests/test_p4d184_joined_value_counts.py": 7.16,
    "tests/test_p4d185_grouped_cells.py": 6.96,
    "tests/test_p4d186_title_rows.py": 0.3,
    "tests/test_p4d187_numbers_stored_as_text.py": 0.96,
    "tests/test_p4d188_sheet_names_in_the_report.py": 0.33,
    "tests/test_p4d189_format_codes_as_written.py": 0.58,
    "tests/test_p4d18_role_topology.py": 0.03,
    "tests/test_p4d18_shape_forms.py": 7.03,
    "tests/test_p4d190_numbers_carry_the_average.py": 3.04,
    "tests/test_p4d191_p4d192_date_counts.py": 7.46,
    "tests/test_p4d193_twice_written_wholes.py": 5.8,
    "tests/test_p4d194_signed_marks.py": 10.42,
    "tests/test_p4d195_width_conventions_named.py": 2.83,
    "tests/test_p4d196_identifier_layout_partners_signs.py": 2.62,
    "tests/test_p4d197_stored_as_text_withheld.py": 1.79,
    "tests/test_p4d198_truth_values_written.py": 14.59,
    "tests/test_p4d19_declared_codes.py": 1.71,
    "tests/test_p4d21_joined_numbers.py": 5.54,
    "tests/test_p4d230_prefixed_partners_wear_named_layouts.py": 1.43,
    "tests/test_p4d233_hexadecimal_prefix.py": 2.92,
    "tests/test_p4d239_forced_counts_of_one.py": 9.58,
    "tests/test_p4d241_record_shape_names_no_column.py": 1.88,
    "tests/test_p4d242_commonest_written_name.py": 0.1,
    "tests/test_p4d243_comma_shape_forms.py": 55.98,
    "tests/test_p4d244_made_up_can_coincide.py": 0.33,
    "tests/test_p4d26_contract_describes_the_producer.py": 0.01,
    "tests/test_p4d26_decimal_comma.py": 2.5,
    "tests/test_p4d27_address_remark.py": 1.86,
    "tests/test_p4d27_note_grammar_matches_the_code.py": 0.04,
    "tests/test_p4d27_token_not_quantity.py": 0.14,
    "tests/test_p4d28_free_text_keeps_its_kind.py": 1.07,
    "tests/test_p4d291_dates_a_reader_opens.py": 2.26,
    "tests/test_p4d298_absorbed_readings.py": 0.51,
    "tests/test_p4d2_loud_decline.py": 0.66,
    "tests/test_p4d30_field_widths.py": 0.85,
    "tests/test_p4d32_empty_bins.py": 8.34,
    "tests/test_p4d411_mode.py": 0.33,
    "tests/test_p4d42_clock_role.py": 1.11,
    "tests/test_p4d43_date_readings.py": 1.2,
    "tests/test_p4d44_unrepresentable_widths.py": 5.91,
    "tests/test_p4d46_day_first.py": 0.19,
    "tests/test_p4d48_kurtosis.py": 0.09,
    "tests/test_p4d4_affixed_role.py": 7.45,
    "tests/test_p4d5_long_tail_labels.py": 5.09,
    "tests/test_p4d61_holes_reproduced.py": 0.53,
    "tests/test_p4d62_machine_artifacts.py": 0.22,
    "tests/test_p4d64_judged_stand_ins_written.py": 24.62,
    "tests/test_p4g3r1_joined_review.py": 25.08,
    "tests/test_p4r13_compound_role.py": 4.87,
    "tests/test_p4r152_one_page_one_answer.py": 0.13,
    "tests/test_p4r1_withdrawn_claims.py": 0.57,
    "tests/test_p4r24_advisory_remarks.py": 1.2,
    "tests/test_p4r34_form_census_per_level.py": 1.13,
    "tests/test_p4r53_recount_population.py": 1.29,
    "tests/test_p4r56_grid_separation.py": 0.63,
    "tests/test_p4r58_joined_numbers.py": 0.74,
    "tests/test_p4r59_unrepresentable_widths.py": 0.04,
    "tests/test_p4r60_hole_spellings.py": 0.16,
    "tests/test_p4r70_the_report_says_what_the_twin_carries.py": 0.2,
    "tests/test_p5r1_the_grain_clause_is_true.py": 0.39,
    "tests/test_profile_document.py": 5.5,
    "tests/test_profile_version_4.py": 0.53,
    "tests/test_profile_version_5.py": 0.99,
    "tests/test_provenance.py": 4.99,
    "tests/test_r6_taxonomy_contract.py": 15.13,
    "tests/test_r6f5_write_transaction.py": 0.01,
    "tests/test_reading.py": 4.55,
    "tests/test_reading_agreement.py": 4.33,
    "tests/test_reading_header_shape.py": 0.01,
    "tests/test_round2_disclosure.py": 14.57,
    "tests/test_round2_numbers_dates.py": 3.26,
    "tests/test_ruling_first_row_not_told.py": 0.74,
    "tests/test_ruling_identifier_prefix.py": 8.82,
    "tests/test_ruling_levels_counted_by_subtraction.py": 5.0,
    "tests/test_ruling_pooled_held_back_levels.py": 5.46,
    "tests/test_shipped_page_review.py": 1.76,
    "tests/test_stage2_dates_as_written.py": 1.19,
    "tests/test_stage2_datetime_oracle.py": 3.11,
    "tests/test_stage2_decimal_comma_readings.py": 0.31,
    "tests/test_stage2_grouping_oracle.py": 0.23,
    "tests/test_stage2_judged_provenance.py": 5.11,
    "tests/test_stage2_nested_grouping_loss.py": 0.72,
    "tests/test_stage2_refusals.py": 0.36,
    # The tail rule of stage 3 (landing 3.3): forty-five cases over ten
    # shapes, each a whole run through the product.
    "tests/test_stage3_tail_rule.py": 52.0,
    "tests/test_stage2_round_trip.py": 21.51,
    "tests/test_stage2_spellings_survive.py": 0.72,
    "tests/test_stage2_summary.py": 0.47,
    "tests/test_stage2_timestamp_spellings.py": 45.86,
    "tests/test_summary_and_properties.py": 4.6,
    "tests/test_taxonomy.py": 0.42,
    "tests/test_twin_golden.py": 2.89,
    "tests/test_u1u2_count_every_present_cell.py": 0.27,
    "tests/test_validate_lock.py": 0.84,
    "tests/test_validation.py": 25.47,
    "tests/test_window_agreement.py": 81.45,
    "tests/test_workbook_dates.py": 14.43,
    "tests/test_workbook_round_trip.py": 114.95,
}
